apiVersion: v1
kind: Service
metadata:
  name: custdemoprod
  labels:
    app: custdemoprod
spec:
  type: ClusterIP
  selector:
    app: custdemoprod
  ports:
    - port: 8090
      targetPort: 8090
    