apiVersion: v1
kind: Service
metadata:
  name: custdemoprod
  namespace: prod
  labels:
    app: custdemoprod
spec:
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30001
  selector:
    app: custdemoprod
